### ISSUE TITLE
Crate evaluation tracking issue

### ISSUE THREAD

**Issue by brson** [alexcrichton/cc-rs#198]
- [ ] [Extract windows_registry module into its own crate](https://github.com/alexcrichton/gcc-rs/issues/174)
- [x] [Implement `Clone`, `Debug` and `Default` for `Config`](https://github.com/alexcrichton/gcc-rs/issues/175)
- [x] [Implement `Clone` and `Debug` for `Tool`](https://github.com/alexcrichton/gcc-rs/issues/176)
- [x] [Add examples for `Config::include`, `define` and `flag`](https://github.com/alexcrichton/gcc-rs/issues/177)
- [x] [Add examples for `shared_flag` and `static_flag`](https://github.com/alexcrichton/gcc-rs/issues/178)
- [x] [Add examples for `cpp_link_stdlib` and `cpp_set_stdlib`](https://github.com/alexcrichton/gcc-rs/issues/179)
- [x] [Add examples for `Config::target` and `Config::host`](https://github.com/alexcrichton/gcc-rs/issues/180)
- [x] [Add panic conditions to various functions](https://github.com/alexcrichton/gcc-rs/issues/181)
- [x] [Add internal hyperlinks to doc prose](https://github.com/alexcrichton/gcc-rs/issues/182)
- [x] [Add readme and categories to Cargo.toml](https://github.com/alexcrichton/gcc-rs/issues/183)
- [x] [Replace `Option<&str>` with `Option<Enum>` in `cpp_link_stdlib` / `cpp_set_stdlib`](https://github.com/alexcrichton/gcc-rs/issues/184)
- [x] [Change `compile` to take just a bare name, not a full file name](https://github.com/alexcrichton/gcc-rs/issues/185)
- [x] [Rename crate](https://github.com/alexcrichton/gcc-rs/issues/186)
- [x] [Clarify behavior of `expand`](https://github.com/alexcrichton/gcc-rs/issues/187)
- [x] [Remove `compile_library` function](https://github.com/alexcrichton/gcc-rs/issues/188)
- [x] [Rename `Config` type](https://github.com/alexcrichton/gcc-rs/issues/189)
- [x] [Add warning control](https://github.com/alexcrichton/gcc-rs/issues/190)
- [ ] [Add control over the C/C++ standard](https://github.com/alexcrichton/gcc-rs/issues/191)
- [x] [Add try_compile and try_expand](https://github.com/alexcrichton/gcc-rs/issues/192)
- [x] [Mention in the crate docs that this crate also supports assembly](https://github.com/alexcrichton/gcc-rs/issues/193)
- [x] [Explain what metadata is emitted by `cargo_metadata`](https://github.com/alexcrichton/gcc-rs/issues/194)
- [ ] [Consider how to expose parallelism](https://github.com/alexcrichton/gcc-rs/issues/195)
- [ ] [Document the `rayon` feature](https://github.com/alexcrichton/gcc-rs/issues/196)
- [x] [Add `files` method](https://github.com/alexcrichton/gcc-rs/issues/199)
- [ ] [Bump to 1.0 (after all else)](https://github.com/alexcrichton/gcc-rs/issues/197)

**Comment by brson** [comment]
@alexcrichton @sfackler I don't have collaborator access. You might tag some of these easy and/or help-wanted.

**Comment by alexcrichton** [comment]
Issues tagged!

**Comment by alexcrichton** [comment]
Finished!
